### ISSUE TITLE
not serving static files correctly

### ISSUE THREAD

**Issue by WhoAdarshPandya** [zhmushan/abc#105]
hi great library 
i tried to render static files with this code

```
app.static("/", "./build/")
  .file("/", "build/index.html")
  .start(
    { port: 2002 },
  );
 ```

but logo and css aren't loading , is there a better way? am i doing it wrong?

**code**

![Screenshot (579)](https://user-images.githubusercontent.com/31694369/90264861-5d85b000-de6f-11ea-8283-f272b977643e.png)

**result**

![Screenshot (580)](https://user-images.githubusercontent.com/31694369/90264903-73937080-de6f-11ea-88dc-ec8c9ce10b70.png)

expected : render all svgs/css/js properly

**Comment by zhmushan** [comment]
@WhoAdarshPandya Thanks your feedback, I fixed it on https://github.com/zhmushan/abc/commit/d856329c5727b5fe072525622ed7b7c9bbe73173

Before this patch is released, you can quickly fix it with the following code:
```ts
import { Application } from "https://deno.land/x/abc@v1.0.2/mod.ts";
import { MIME } from "https://deno.land/x/abc@v1.0.2/constants.ts";

MIME.DB[".svg"] = "image/svg+xml";

const app = new Application();
app.static("/", "./build/")
  .file("/", "build/index.html")
  .start(
    { port: 2002 },
  );
```

**Comment by WhoAdarshPandya** [comment]
Hey @zhmushan Thank you for the solution , it's working now, i must say **abc**  has same flavor of express , and that helps lots of node developers! Amazing!!!
