### ISSUE TITLE
Intentional? Contex.body() seems to be unreadable after a middleware already handled it.

### ISSUE THREAD

**Issue by ItsJustMeChris** [zhmushan/abc#109]
Middleware.ts

```ts
export default (next: HandlerFunc): HandlerFunc => async (context: Context) => {
  const { token } = await context.body();
  console.log(token);
  return next(context);
};
```

controller.ts

```ts
const create = async (context: Context): Promise<any> => {
    try {
        const { title } = await context.body();
        console.log(title);
        return title;
    } catch (error) {
        console.log(error);
        return {};
    }
}

export {
    create,
}
```

route.ts 

```ts
import middleware from 'middleware.ts';

export default (group: Group): void => {
    group.post('/new', create, middleware);
}
```

index.ts

```ts
import routeGroup from 'route.ts';

routeGroup(app.group('test'));
```

The code above is stripped out of context and dumbed down a bit to show the programmatic flow, so it may not 'just work' to test, but it should be enough to get the gist of the issue. I might be making a mistake somewhere also, I'll update if I manage to resolve it -- or I notice it to be intentional and there's another step I've missed.

**Comment by ItsJustMeChris** [comment]
Looking at it further it seems like it has to do with context.request.body. Still not 100% sure. 


As a slight tangent, the request is a post;the variables are existent in the middleware, removing middleware allows them to come through to the controller. I am setting context.set() from the middleware which is a step I didn't include in the original report.

**Comment by zhmushan** [comment]
In `deno_std`, the body can only be awaited once, and `Abc` doesnt do any on it (in fact, I should do

**Comment by zhmushan** [comment]
fixed on https://github.com/zhmushan/abc/commit/863e7d2a0da3b841952e488bd13c03acced7735f
