### ISSUE TITLE
error: Uncaught SyntaxError: The requested module './constants.ts' does not provide an export named 'MIME'

### ISSUE THREAD

**Issue by adrai** [zhmushan/abc#115]
When I run this example: https://github.com/i18next/i18next-http-backend/tree/master/example/deno
it seems to work like expected, without any problem.

But when I run the deno tests: `deno test test/deno/*.js --allow-net` (https://github.com/i18next/i18next-http-backend/tree/master/test/deno)

I get this error: `error: Uncaught SyntaxError: The requested module './constants.ts' does not provide an export named 'MIME'`

Like here: https://github.com/i18next/i18next-http-backend/runs/1148469490?check_suite_focus=true

Any idea why this is happening? https://github.com/zhmushan/abc/blob/ce7954710d5c8cd895750b60527a360655c3cd80/constants.ts#L61

**Comment by zhmushan** [comment]
I have no idea....I tried to extract the code in the test, but I got the following error:
```
error: TS2304 [ERROR]: Cannot find name 'global'.
  if (typeof global !== 'undefined' && global.fetch) {
             ~~~~~~
    at file:///mnt/c/Users/MuShan/Desktop/i18next-http-backend/lib/getFetch.cjs:3:14
```

**Comment by adrai** [comment]
Do you have the ltest Deno version?

**Comment by zhmushan** [comment]
@adrai After I upgraded deno to the latest version, the test passed. . . .

**Comment by adrai** [comment]
strange...
now it works for me too

**Comment by adrai** [comment]
But on github it still fails: https://github.com/i18next/i18next-http-backend/runs/1353083327

![image](https://user-images.githubusercontent.com/1086194/98118618-cba8a480-1eab-11eb-8e43-8829863d0c6a.png)

idk

**Comment by zhmushan** [comment]
@adrai Although I don’t know why, but after I removed the "no-check", the test passed. see https://github.com/zhmushan/i18next-http-backend/runs/1353130447?check_suite_focus=true

**Comment by adrai** [comment]
omg, you're right!!
![image](https://user-images.githubusercontent.com/1086194/98120016-b3398980-1ead-11eb-80a3-c44ea8295612.png)

**Comment by adrai** [comment]
Thank you for the hint
