### ISSUE TITLE
error: Uncaught SyntaxError: The requested module './constants.ts' does not provide an export named 'MIME'

### ISSUE THREAD

**Issue by xyb851** [zhmushan/abc#117]
```ts
import {Application}from "https://deno.land/x/abc@v1.2.1/mod.ts";

const app = new Application();

app
  .get("/hello", (c) => {
    return "Hello, Abc!";
  })
  .start({ port: 8080 });
```
Running errors:
`error: Uncaught SyntaxError: The requested module './constants.ts' does not provide an export named 'MIME'`
deno version: v1.5.2
abc version: v1.2.1

**Comment by zhmushan** [comment]
I can't reproduce.

**Comment by xyb851** [comment]
This error will only appear after deno is enabled with the "--no-check" option

**Comment by zicklag** [comment]
I just ran into this, and strangely enough, like @xyb851 said, it only happens when passing in --no-check. :shrug:

**Comment by zhmushan** [comment]
This error is caused by `deno`. It is recommended not to carry the `nocheck` flag before waiting for `deno` to be fixed.
For more details see: https://github.com/denoland/deno/issues/8478

**Comment by zhmushan** [comment]
I removed namespace in v1.2.3, and now we can use `nocheck` and `bundle` freely.
cc @michailVestnik
