### ISSUE TITLE
Bundle ABC.js error 

### ISSUE THREAD

**Issue by michailVestnik** [zhmushan/abc#118]
Hello!

I take a few steps: 
1. deno bundle 'https://deno.land/x/abc@v1.2.2/mod.ts' ABC.js
2. start a 'my_app.js' with import local ABC.js
3. ... and see the error
but if run my_app.js with import 'https://deno.land/x/abc@v1.2.2/mod.ts' everything works fine!
What could be the problem? Please tell me!

And how start ABC with TLS? 

app.startTLS({
    hostname: 'localhost',
    port: 8080,
    certFile: 'localhost.crt',
    keyFile: 'localhost.key',
})

thank you in advance for your response!

**Comment by zhmushan** [comment]
The cause of this issue is consistent with #117, we must first wait for https://github.com/denoland/deno/issues/8478 to be fixed.
