### ISSUE TITLE
Add wasm in MIME-types

### ISSUE THREAD

**Issue by michailVestnik** [zhmushan/abc#119]
Hi, i test simple example from https://developer.mozilla.org/ru/docs/WebAssembly/Using_the_JavaScript_API, and get the error "response has unsupported MIME types"
I added application/wasm in 4 places in ABC.js final bundle and everything is working well now!
screenshot: https://user-images.githubusercontent.com/75129392/102251578-5fa86a00-3f48-11eb-8f8c-b70d545810cd.jpg

I think, you may want to add this MIME in the next update so that other developers do not encounter this error!

**Comment by zhmushan** [comment]
fixed on https://github.com/zhmushan/abc/commit/df36b1baff6495b15c44c7681373a058cd9f2054
