### ISSUE TITLE
Need info! Uploading files

### ISSUE THREAD

**Issue by michailVestnik** [zhmushan/abc#122]
Hi!
I run simple example 

```
form.addEventListener('submit', (event) => {
        event.preventDefault()
	const data = new FormData()
	data.append('file', file.files[0])
	fetch('/action', {
		method: 'POST',
		body: data,
	})
})
```

and server 

```
app.post('/action', async (context) => {
	const data = await context.body
})
```

and see the 500 internal error.

could you add a simple example of how to accept files to the server?

**Comment by zhmushan** [comment]
no problem

**Comment by zhmushan** [comment]
Hi @michailVestnik, did you forget to carry the `--allow-net`? Or the "multipart/form-data" request header was not provided in the request?

I just tried a few different ways to upload files, all without errors. And, I also made a simple example, see https://github.com/zhmushan/abc/commit/b27bf15abfa128147e32f471586fdfdf687dc139

**Comment by michailVestnik** [comment]
Thank you!
