### ISSUE TITLE
Doubts about allowOrigins

### ISSUE THREAD

**Issue by wolf-leo** [zhmushan/abc#125]
when I use 
`const config: CORSConfig = {
  allowOrigins: ["*"],
};
const app = new Application();
const port = 8000;
app.use(cors(config));`

start successfully. you can visit it on http://localhost:8000
That will be successed

**### but when I do this, got error**

`
const config: CORSConfig = {
  allowOrigins: ["http://abc.com"],
};
const app = new Application();
const port = 8000;
app.use(cors(config));
`

`TypeError: Cannot read property 'startsWith' of null
    at cors.ts:52:20
    at Application.#transformResult (app.ts:241:22)
    at Application.#start (app.ts:71:28)`

**Comment by zhmushan** [comment]
Fixed in https://github.com/zhmushan/abc/commit/ddffb2240d6ce6fce2497e8226b0c36ab81da2fd

Thank you for letting me notice this problem, I have fixed it, and will add support for wildcards in the next change.
