### ISSUE TITLE
groups & middlewares

### ISSUE THREAD

**Issue by eco747** [zhmushan/abc#126]
Hello,
I just try to define a middleware for a specific group, so I use this code:

```
function setupUsersGroup( g: Group ) {

	g.get	( '/', 		list );
	g.get	( '/:id', 	get );

	g.use( checkIfUserIsLogged);
}
```

but I get an exception:
Uncaught Error: a function is already registered for path "users"

Did I miss something ?

Regards
Etienne

**Comment by zhmushan** [comment]
Sorry, this is a bug introduced after the router upgrade, I will fix it.

**Comment by zhmushan** [comment]
Sorry I'm late. This has been fixed in https://github.com/zhmushan/abc/commit/629d6c1b711c89fcdc0992f9a296645df00e805b.
