### ISSUE TITLE
Add text/css MIME-type

### ISSUE THREAD

**Issue by YasminaKarad** [zhmushan/abc#127]
# Issue

Hi. when the page loads, in console I see a browser warning.

![Screenshot_1](https://user-images.githubusercontent.com/79387487/110188947-de82b400-7e60-11eb-936a-8c5b120f42de.png)

Translated, this means that the resource is interpreted as a stylesheet, but load as text/plain.
specifying the type in html does not bring results

`<link rel="stylesheet" type="text/css" href="CSS/style.css" />`

Please add a text/css in https://deno.land/x/abc@v1.2.6/_mime.ts

**Comment by zhmushan** [comment]
Added, see https://github.com/zhmushan/abc/commit/4e237bd57ffbca760470a473e05b4a7feae9c290

Before this patch is released, you can quickly fix it with the following code:

```ts
import { MIME } from "https://deno.land/x/abc@v1.2.6/constants.ts";
MIME.DB[".css"] = "text/css";
```
