### ISSUE TITLE
Error: socket hang with CustomException

### ISSUE THREAD

**Issue by sidratul** [zhmushan/abc#128]
I create custom exception, but when I test on postman, the server returns no response and shows Error: socket hang up but when I use the provided exception it works well.

```
export class InvalidTokenException extends HttpException {
  constructor() {
    super("Invalid token", Status.InvalidToken);
  }
}

new InvalidTokenException("message") //not work
new UnauthorizedException("messgae") // works
```
Is this a bug or I implemented it the wrong way?

Edit:
The Status.InvalidToken is custom number which is 498, i found out this is the cause of error.
When I set the status = 404 then it works well.

Can we set a custom status code?

**Comment by zhmushan** [comment]
This is not an issue of Abc, currently Deno only allows [standard http status codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)
