### ISSUE TITLE
Closing Server While Using Webview

### ISSUE THREAD

**Issue by wwderw** [zhmushan/abc#131]
I'm using the server to bootstrap an app that uses WASM for logic and using webview for the UI rendering.

Is there a way to close the server when closing the webview window?

Right now I have something like this:

const app = new Application(); 

app.static('/', 'views').file('/', 'views/index.html').start({ port: 8000 }); 

const webview = new Webview({url: 'http://localhost:8000/index.html', 
title: 'title', height: 750, width:350, debug: false, resizable: false}); 

webview.run(({event}) => { 
	switch (event){
		case 'close':
			Deno.close(); //I have tried webview.drop() and app.close() as well

		case 'domContentLoaded':
			console.log('Program Ready!');
			break;
	}; 
});

What ends up happening is that when I close out, the webview window hangs for a few moments and then I get an OS msg to kill the window.

Is there a way to stop the server when closing out the webview (and if not, could that functionality be added)?  If its not as simple as my logic is just not right.

Thanks for the help!

**Comment by zhmushan** [comment]
I don't know how to use `webview_deno`, but if you can execute `await app.close()` before the window is closed, the port will be closed normally.

**Comment by wwderw** [comment]
That was it.

I just had to set webview.run() to await webview.run() and then I did await app.close() and it worked like a charm.  Thanks for the help!
