### ISSUE TITLE
error on build 

### ISSUE THREAD

**Issue by esharmony** [zhmushan/abc#36]
Just followed the basic hello worlds and getting these errors

error TS2694: Namespace 'Deno' has no exported member 'ReadResult'.

► https://deno.land/std@v0.9.0/io/bufio.ts:7:24

7 type ReadResult = Deno.ReadResult;
                         ~~~~~~~~~~

error TS2339: Property 'nread' does not exist on type 'number'.

► https://deno.land/std@v0.9.0/io/bufio.ts:134:19

134         assert(rr.nread >= 0, "negative read");

**Comment by zhmushan** [comment]
It looks like std@v0.9.0 can't run on deno@v0.15.0.
