### ISSUE TITLE
Troubles running the example 

### ISSUE THREAD

**Issue by mknet** [zhmushan/abc#37]
Heyho @zhmushan,

I'm trying to run the example described in the README.

If I'm using the first import example I get

`Compiling /Users/marcel/Development/marcelkoch_net/mailer/deno-contact-mailer/main.ts
Downloading https://deno.sh/abc/mod.ts
Downloading http://deno.sh/abc/abc.ts
Downloading http://deno.sh/abc/context.ts
Downloading http://deno.sh/abc/router.ts
Downloading http://deno.sh/abc/binder.ts
Downloading http://deno.sh/abc/deps.ts
Downloading http://deno.sh/abc/group.ts
Downloading http://deno.sh/abc/http_exception.ts
Downloading https://deno.land/std@v0.20.0/fs/path.ts
Downloading https://deno.land/std@v0.20.0/http/server.ts
Downloading https://deno.land/std@v0.20.0/http/http_status.ts
Downloading https://denolib.com/denolib/qs@v1.0.1/mod.ts
Downloading http://deno.land/std@v0.20.0/fs/path/mod.ts
Downloading http://deno.land/std@v0.20.0/fs/path/interface.ts
Downloading http://deno.land/std@v0.20.0/fs/path/win32.ts
Downloading http://deno.land/std@v0.20.0/fs/path/posix.ts
Downloading http://deno.land/std@v0.20.0/fs/path/constants.ts
Downloading http://deno.land/std@v0.20.0/fs/path/utils.ts
Downloading http://deno.land/std@v0.20.0/io/bufio.ts
Downloading http://deno.land/std@v0.20.0/textproto/mod.ts
Downloading http://deno.land/std@v0.20.0/testing/asserts.ts
Downloading http://deno.land/std@v0.20.0/util/async.ts
Downloading http://deno.land/std@v0.20.0/io/util.ts
Downloading http://deno.land/std@v0.20.0/strings/mod.ts
Downloading http://deno.land/std@v0.20.0/strings/encode.ts
Downloading http://deno.land/std@v0.20.0/strings/decode.ts
Downloading http://deno.land/std@v0.20.0/strings/pad.ts
Downloading http://deno.land/std@v0.20.0/fmt/colors.ts
Downloading http://deno.land/std@v0.20.0/testing/diff.ts
Downloading http://deno.land/std@v0.20.0/testing/format.ts
Downloading http://denolib.com/denolib/qs@v1.0.1/formats.ts
Downloading http://denolib.com/denolib/qs@v1.0.1/parse.ts
Downloading http://denolib.com/denolib/qs@v1.0.1/stringify.ts
Downloading http://denolib.com/denolib/qs@v1.0.1/stringify.ts.ts
Downloading http://denolib.com/denolib/qs@v1.0.1/stringify.ts.js
NotFound: Cannot resolve module "./stringify.ts" from "/Users/marcel/.deno/deps/denolib.com/denolib/qs@v1.0.1/mod.ts"
    at maybeError (deno/js/errors.ts:38:12)
    at maybeThrowError (deno/js/errors.ts:26:15)
    at sendSync (deno/js/dispatch.ts:70:5)
    at Object.codeFetch (deno/js/os.ts:33:19)
    at DenoCompiler.resolveModule (deno/js/compiler.ts:501:38)
    at DenoCompiler._resolveModuleName (deno/js/compiler.ts:329:33)
    at moduleNames.map.name (deno/js/compiler.ts:632:33)
    at Array.map (<anonymous>)
    at DenoCompiler.resolveModuleNames (deno/js/compiler.ts:624:24)
    at Object.compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:114975:117)`

If I use the second import (from deno.land instead of deno.sh) I get the following:

`Downloading https://deno.land/x/abc/mod.ts
Downloading http://deno.land/x/abc/abc.ts
Downloading http://deno.land/x/abc/context.ts
Downloading http://deno.land/x/abc/router.ts
Downloading http://deno.land/x/abc/binder.ts
Downloading http://deno.land/x/abc/deps.ts
Downloading http://deno.land/x/abc/group.ts
Downloading http://deno.land/x/abc/http_exception.ts
Downloading http://denolib.com/denolib/qs@v1.0.1/stringify.ts
Downloading http://denolib.com/denolib/qs@v1.0.1/utils.ts
Downloading http://deno.land/x/abc/type.ts
Downloading http://deno.land/x/abc/reflect.ts
Downloading http://deno.land/x/abc/parser.ts
Compiling https://deno.land/x/abc/mod.ts
Compiling http://deno.land/x/abc/abc.ts
/Users/marcel/.deno/deps/deno.land/x/abc/abc.ts:15:45 - error TS2503: Cannot find namespace 'Deno'.`

`15   render<T>(name: string, data: T): Promise<Deno.Reader>;
                                               ~~~~
/Users/marcel/.deno/deps/deno.land/x/abc/abc.ts:51:44 - error TS2304: Cannot find name 'URL'.

51       const c = context({ r: req, url: new URL(req.url, addr), abc: this });`

Those are my `deno -v` outputs:

`deno: 0.1.9
v8: 7.1.302.4
typescript: 3.1.3`

I'm using a Mac running 10.14.

As far as I get it you also ported qs to deno. So, I thought it might help you if I would open the issue at here with all the context.

Let me know if I can help you to get rid of the issue.

Thx in advance for your effort

**Comment by zhmushan** [comment]
deno@v0.20.0 has some breaking changes, which caused std to not work.
you can try to upgrade deno version first.

**Comment by mknet** [comment]
Oh dear, my fault. I thought I'd run deno from my homebrew cellar but ran the one I installed via the shell installer before

**Comment by mknet** [comment]
Works like a charm with deno 0.21. Thx again
