### ISSUE TITLE
Running the example app ends in error

### ISSUE THREAD

**Issue by Rebstorm** [zhmushan/abc#38]
Hi, 

Im not sure where else to post it, SO doesnt really wish to help and I figured id see you were able to help. 

Whenever I try to run the example below on the webpage: 

```
import { abc } from "https://deno.sh/abc/mod.ts";
// OR import { abc } from "https://deno.land/x/abc/mod.ts";

const app = abc();

app
  .get("/hello", c => {
    return "Hello, Abc!";
  })
  .start("0.0.0.0:8080");
```

then run it: `deno ./server.ts --allow-net`

Results in a: 

```
error TS2345: Argument of type 'Uint8Array | unique symbol' is not assignable to parameter of type 'BufferSource'.
  Type 'unique symbol' is not assignable to type 'BufferSource'.

► https://deno.land/std@v0.20.0/io/bufio.ts:218:37

218     return new TextDecoder().decode(buffer || undefined);
``` 

Is ABC implementing a weird version of the TextDecoder, or does this have to do with my local TS version?

**Comment by zhmushan** [comment]
Thanks, this is caused by the different versions of deno & std.

**Comment by zhmushan** [comment]
#39

**Comment by Rebstorm** [comment]
Thank you @zhmushan !
