### ISSUE TITLE
Example template not working

### ISSUE THREAD

**Issue by martinlevesque** [zhmushan/abc#44]
Hey, 

Tested https://deno.land/x/abc/examples/02_template/main.ts

With the Deno version I am using 

--
# deno --version
deno 0.30.0
v8 8.1.108
typescript 3.7.2
--

It fails with:

deno_1  | error TS2322: Type 'void' is not assignable to type 'string'.
deno_1  | 
deno_1  | ► file:///opt/app/http-abc.ts:15:5
deno_1  | 
deno_1  | 15     return await c.render("./index.html", { name: "zhmushan" })

**Comment by zhmushan** [comment]
Thanks, it should be:
```ts
app
  .get("/", (c: Context): string => {
    c.render("./index.html", { name: "zhmushan" })
  })
  .start({ port: 8080 });
```
This is due to a mistake when adding the lost type in the last update. I will fix it.
