### ISSUE TITLE
Unable to respond with HTTP Headers

### ISSUE THREAD

**Issue by alexjamesmalcolm** [zhmushan/abc#47]
I would like to attach the `Last-Modified` HTTP header to a response. Does abc support this? https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified

**Comment by zhmushan** [comment]
We can do this by setting `response.headers`, but now we should initialize header manually:
```ts
app.get("/", c => {
  c.response.headers = new Headers();
  c.response.headers.append("key", "value");
});
```
I have sent a pr #48 , headers are initialized by default

**Comment by alexjamesmalcolm** [comment]
Closing as abc does support returning HTTP headers and was made easier by #48.
