### ISSUE TITLE
'https://deno.land/std/media_types/mod.ts' failed: 404 Not Found

### ISSUE THREAD

**Issue by t-yng** [zhmushan/abc#57]
I tried to execute Hello World example code.

I encountered not found module error.
'https://deno.land/std/media_types/mod.ts' failed: 404 Not Found

The media_types module repository is missing now.
https://github.com/denoland/deno/tree/master/std/media_types/mod.ts

index.ts
```typescript
import { Application } from "https://deno.land/x/abc/mod.ts";

const app = new Application();

app
.get("/hello", c => {
    return "Hello, Goobye!"
})
.start( {port: 8080});
```

execute result
```
$ deno --allow-net index.ts
Compile file:///Users/tomohiro/workspace/deno/abc-sample/index.ts
Download https://deno.land/std@v0.38.0/http/server.ts
Download https://deno.land/std@v0.38.0/http/http_status.ts
Download https://deno.land/std/media_types/mod.ts
error: Uncaught Error: Import 'https://deno.land/std/media_types/mod.ts' failed: 404 Not Found
► $deno$/ops/dispatch_json.ts:43:11
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at sendAsync ($deno$/ops/dispatch_json.ts:98:10)
```

**Comment by t-yng** [comment]
/std/media_types was moved.
https://github.com/denoland/deno/commit/13db64fbc6a8da68e5f6c1da59e058a1a3146054

**Comment by zhmushan** [comment]
@t-yng I prefer to follow `file_server`'s behavior.
So I will write a `contentType` method and remove the dependency of `media_types`.

**Comment by t-yng** [comment]
@zhmushan 
Thank you.
I hope to your change.  😊

**Comment by zhmushan** [comment]
Fixed in https://github.com/zhmushan/abc/commit/9eefba9942bd27ec185103c8abb011705a6ffe7b
