### ISSUE TITLE
Support parsing form body

### ISSUE THREAD

**Issue by zhmushan** [zhmushan/abc#58]
In `context.body()`, we simply use `JSON.parse()` to parse the data. Now we should enhance this method so that it can process the data from the form. I think this is a good start for contributing to `abc`.

**Comment by shuminyang** [comment]
Hi, I'm interested in help, can I work on this?

**Comment by zhmushan** [comment]
@shuminyang Of course! Fell free to pr

**Comment by zhmushan** [comment]
@shuminyang Hi, do you have any progress? I plan to implement it before 1.0

**Comment by shuminyang** [comment]
Hi @zhmushan, sorry for taking so long, it's my first time doing something like this.
I had a couple of this in mind and don't know if I've done thing as you expected.

this is a PR in my fork, if you wanna take a look
https://github.com/shuminyang/abc/pull/1/files
Unit testing is missing, but is the next thing to do right after. Any feedback is very appreciated!

**Comment by zhmushan** [comment]
I approve a part, you can send pr directly to my repo, I will propose a modification

**Comment by zhmushan** [comment]
@shuminyang `readForm` has been included in `MultipartReader`, we don;t need to re-implement it. I made a simple implementation about `body` of your reference.
```ts
  async body(): Promise<Record<string, unknown>> {
    let data: Record<string, unknown> = {};
    const contentType = this.request.headers.get(Header.ContentType);

    if (contentType) {
      if (contentType.includes(MIME.ApplicationJSON)) {
        data = JSON.parse(decoder.decode(await readAll(this.request.body)));
      } else if (contentType.includes(MIME.ApplicationForm)) {
        for (const [k, v] of new URLSearchParams(
          decoder.decode(await readAll(this.request.body))
        )) {
          data[k] = v;
        }
      } else if (contentType.includes(MIME.MultipartForm)) {
        const match = contentType.match(/boundary=([^\s]+)/);
        const boundary = match ? match[1] : undefined;
        if (boundary) {
          const mr = new MultipartReader(this.request.body, boundary);
          const form = await mr.readForm();
          for (const [k, v] of form.entries()) {
            data[k] = v;
          }
        }
      }
    }

    return data;
  }
```

**Comment by shuminyang** [comment]
Oh wait, so the readForm already does the trick?
