### ISSUE TITLE
Support for redirects.

### ISSUE THREAD

**Issue by brianraila** [zhmushan/abc#59]
At the moment is one able to carry out redirects to other URLs from the HandlerFunc.

**Comment by zhmushan** [comment]
`redirect(url: string, code: Status)` should be implemented as a method in `Context`

**Comment by zhmushan** [comment]
@brianraila see https://github.com/zhmushan/abc/commit/b9a251b3d9b9d0310dac87bea6bbebb481b42d9f

**Comment by brianraila** [comment]
Thanks for that Sir.
