### ISSUE TITLE
async middleware

### ISSUE THREAD

**Issue by adrai** [zhmushan/abc#60]
Is there a way to add an asynchronous middleware?

i.e. 

```js
app.use((next) =>
  (c) => {
    invokeSomethingAsync((fetched) => {
       next(c)
    })
  }
)
```

**Comment by zhmushan** [comment]
Do you mean this?
```ts
app.use((next) =>
  async (c) => {
    await sleep(1000);
    return next(c);
  }
);
```

**Comment by adrai** [comment]
have a callback based api..., but yes

**Comment by adrai** [comment]
fyi: just added some deno tests: https://github.com/i18next/i18next-http-middleware/tree/master/test/deno

**Comment by zhmushan** [comment]
That's cool!

**Comment by adrai** [comment]
Now abc has an i18next middleware too 😉
