### ISSUE TITLE
does not provide an export named 'HandlerFunc'

### ISSUE THREAD

**Issue by sajanthomas01** [zhmushan/abc#62]
error: Uncaught SyntaxError: The requested module 'https://deno.land/x/abc/mod.ts' does not provide an export named 'HandlerFunc'

**Comment by zhmushan** [comment]
It works for me
![image](https://user-images.githubusercontent.com/24505451/81458378-acff7480-91cc-11ea-9326-2ca15e5c50a6.png)

**Comment by sajanthomas01** [comment]
@zhmushan But when I run the file, it's showing me the following error 
![Screenshot from 2020-05-09 19-40-54](https://user-images.githubusercontent.com/32977170/81476182-11065500-922e-11ea-9c38-de44ec51f90c.png)

**Comment by zhmushan** [comment]
You can try to run with `--reload`.

**Comment by zhmushan** [comment]
I'm gonna close this issue now. fell free to reopen if you have any questions
