### ISSUE TITLE
How to show type definition in VScode?

### ISSUE THREAD

**Issue by gjuoun** [zhmushan/abc#63]
It's a pain not having type hint in VScode. Can someone tell me how to make it happen?

![image](https://user-images.githubusercontent.com/8935612/81642037-d13f9900-93f8-11ea-858e-832b11a5374d.png)

**Comment by gjuoun** [comment]
Okay, I end up to clone the whole repo to make it work...

![image](https://user-images.githubusercontent.com/8935612/81642332-8c683200-93f9-11ea-8c20-29655706f49d.png)

**Comment by zhmushan** [comment]
![image](https://user-images.githubusercontent.com/24505451/81648079-a9841b80-9460-11ea-937d-f65130ed7d8e.png)
@gjuoun It's a `vscode_deno`'s issue
