### ISSUE TITLE
Wildcard route is conflicting when creating a route to cover generic path

### ISSUE THREAD

**Issue by shuminyang** [zhmushan/abc#67]
Hi,

I just realised that if you try to create a generic route to cover a entire path the app will break if you have a second and more specific route. One exemple:

```typescript
const app = new Application()

app.get("/hello/:param", (req: Context) => {
    console.log(req.params)
    return `Hello, ${req.params}`
})

app.get("/:param", (req: Context) => {
    console.log(req.params)
    return `Hello2, ${req.params}`
})

app.start({port: 8080})
```

This will give you an error like:

```typescript
error: Uncaught Error: wildcard route ':param' conflicts with existing children in path '/:param'
        throw new Error(
              ^
    at Node.insertChild (node.ts:269:15)
    at Node.addRoute (node.ts:183:16)
    at Router.add (router.ts:20:10)
    at Application.add (app.ts:143:17)
    at Application.get (app.ts:89:17)
    at Testing.ts:11:5
```

I believe that' s not intended

**Comment by zhmushan** [comment]
In fact, it was designed :P, but I also realized it was very inconvenient, and I needed a little time to correct this.

**Comment by zhmushan** [comment]
Need to be informed: before discussing params conflicts, I need to solve the static routing priority issue (see https://github.com/zhmushan/router/issues/1)

**Comment by shuminyang** [comment]
should we close this issue and open it on the new route repo?

**Comment by shuminyang** [comment]
also I've been looking into this and got a I'm trying to figure out why the moment you solve the conflict between this two routes
`/route` and `/:generic` this one becomes a problem
`/:generic` and `/route/:param`. 
Was this designed as well?

**Comment by zhmushan** [comment]
In the new router design, we will always match the static route first.

For your situation:
```
/route/foo     match
/foo               match
/foo/bar        no match
/router/foo    no match
```

**Comment by zhmushan** [comment]
@shuminyang @Jipfr Fixed in https://github.com/zhmushan/abc/commit/ad63d65ec0f73bfeabc3bc80fb1ae6ae5e25904f
