### ISSUE TITLE
Parameter 'c' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by JipFr** [zhmushan/abc#70]
I'm trying to use abc in a chat site I'm working on, switching over from another web library for Deno.

I'm importing the library like so
```typescript
import { Application, Context } from "https://deno.land/x/abc@v1.0.0-rc3/mod.ts";
import { cors } from "https://deno.land/x/abc@v1.0.0-rc3/middleware/cors.ts";
```
However, I'm getting

```
error: TS7006 [ERROR]: Parameter 'c' implicitly has an 'any' type.
        h = (c) => {
             ^
    at https://deno.land/x/abc@v1.0.0-rc3/app.ts:39:14

TS7006 [ERROR]: Parameter 'c' implicitly has an 'any' type.
    const h: HandlerFunc = (c) => {
                            ^
    at https://deno.land/x/abc@v1.0.0-rc3/app.ts:170:29

TS7006 [ERROR]: Parameter 'c' implicitly has an 'any' type.
    return this.get(path, (c) => c.file(filepath), ...m);
                           ^
    at https://deno.land/x/abc@v1.0.0-rc3/app.ts:180:28

TS7006 [ERROR]: Parameter 'c' implicitly has an 'any' type.
    return (c) => {
            ^
    at https://deno.land/x/abc@v1.0.0-rc3/middleware/cors.ts:33:13

Found 4 errors.
```
Am I importing a wrong version, or is this an issue with the module?

**Comment by zhmushan** [comment]
@JipFr Hi, what's your deno version

**Comment by JipFr** [comment]
Here's my version information

deno 1.0.0-rc3
v8 8.4.300
typescript 3.8.3

**Comment by zhmushan** [comment]
@JipFr This is a bug of TypeScript 3.8, you need to upgrade deno to 1.0.0

**Comment by JipFr** [comment]
Running `deno upgrade` tells me I have the latest version.
```
Checking for latest version
Local deno version 1.0.0-rc3 is the most recent release
```
Should I re-install Deno?

**Comment by zhmushan** [comment]
> Running `deno upgrade` tells me I have the latest version.
> 
> ```
> Checking for latest version
> Local deno version 1.0.0-rc3 is the most recent release
> ```
> 
> Should I re-install Deno?

Maybe you should. (I think this is a deno issue😂

**Comment by JipFr** [comment]
I have upgraded Deno and removed the module cache, however I now get 
```
error: Uncaught Error: wildcard route '*filepath' conflicts with existing children in path '/*filepath'
        throw new Error(
              ^
    at Node.insertChild (https://deno.land/x/abc@v1.0.0-rc3/node.ts:269:15)
    at Node.addRoute (https://deno.land/x/abc@v1.0.0-rc3/node.ts:183:16)
    at Router.add (https://deno.land/x/abc@v1.0.0-rc3/router.ts:21:10)
    at Application.add (https://deno.land/x/abc@v1.0.0-rc3/app.ts:151:17)
    at Application.get (https://deno.land/x/abc@v1.0.0-rc3/app.ts:97:17)
    at Application.static (https://deno.land/x/abc@v1.0.0-rc3/app.ts:175:17)
    at file:///Users/jip/Desktop/talk-client/main.ts:103:5
```

I'm running versions
```
deno 1.0.0
v8 8.4.300
typescript 3.9.2
```

And the line on 103 is
```
app.static("/", "./public", cors());
``` 
Is it possible that the cors middleware is maybe outdated?

**Comment by zhmushan** [comment]
Could you show all the code, I have no errors locally

**Comment by JipFr** [comment]
Yes of course. It's all available at https://github.com/JipFr/spreed-client/tree/abc

**Comment by zhmushan** [comment]
@JipFr This is the same as #67 
At the beginning of the design, I thought routing should be clear and unambiguous, but it seems to cause a lot of inconvenience

**Comment by JipFr** [comment]
I see. Is there any way for me to accomplish what I want with the current module version? If not, will you be updating the module, or should I see if there is another module which would allow me to do this?

**Comment by zhmushan** [comment]
quick fix: `app.static("/public", "./public", cors());`
Or try to write static middleware yourself, avoid using wildcards.
I plan to correct the design of the route to make it more logical.

**Comment by JipFr** [comment]
Okay, that works for now! Will you let me know if you update the module to act more like Express would in this case?

**Comment by zhmushan** [comment]
Of course, you can also subscribe to #67 to get the latest progress

**Comment by JipFr** [comment]
Done!
