### ISSUE TITLE
Acting as a proxy for images

### ISSUE THREAD

**Issue by JipFr** [zhmushan/abc#72]
I'm trying to use abc to act as a proxy for images, since they require authentication. Now, fetching them with the required auth works, and I get the images and such, but I can't figure out how to get abc to actually return it as an image. Any help would be appreciated. 

I have 
```javascript
app.get("/image/:id", async (ctx) => {

	let avatarReq = await fetch(`https://myurl.com/avatar/${ctx.params.id}/256`, {
		headers: {
			"Ocs-Apirequest": "true",
			"Accept": "application/json, text/plain, */*",
			"Authorization": `Basic ${ctx.queryParams.auth}`
		}
	});
	// The above request will succeed

	// Now what?
});
```
but have no idea how to proceed. Again, any help would be appreciated!

**Comment by zhmushan** [comment]
You can directly return the image (Uint8Array) in abc@1.0.0-rc5.
Internally, `abc` calls `c.blob()`

**Comment by JipFr** [comment]
Forgive me for not understanding properly, but what am I doing wrong?
```typescript
app.get("/image/:id", async (ctx) => {
	// TODO make this work lol
	let avatarReq = await fetch(`https://box.ictmaatwerk.com/avatar/${ctx.params.id}/256`, {
		headers: {
			"Ocs-Apirequest": "true",
			"Accept": "application/json, text/plain, */*",
			"Authorization": `Basic ${ctx.queryParams.auth}`
		}
	});
	// This will succeed
	let buffer = await avatarReq.arrayBuffer();
	let arr = new Uint8Array(buffer);
	console.log(arr);
	return arr;
});
```
Logging `arr` returns a very large Uint8Array (13781 long), but when I return it it shows in the network tab on my client as JSON, with no response body. Any ideas?

**Comment by zhmushan** [comment]
@JipFr you should update abc to 1.0.0-rc5

**Comment by JipFr** [comment]
Ah, I missed that. Your patch worked, thank you! Images are now loading!
