### ISSUE TITLE
in Post request context.body() returns nothing.

### ISSUE THREAD

**Issue by ShahrozTanveer** [zhmushan/abc#73]

**Comment by zhmushan** [comment]
Check if there is `application/json` in the request header

**Comment by ShahrozTanveer** [comment]
yes

![Post](https://user-images.githubusercontent.com/31120765/82143670-fb60e300-985e-11ea-8ddb-2c3374ebe01a.png)

**Comment by zhmushan** [comment]
Could you show the code

**Comment by ShahrozTanveer** [comment]
this is my repo: https://github.com/ShahrozTanveer/Deno-HelloWorld
context.body is used in /controllers/post.ts

Thank you.

**Comment by zhmushan** [comment]
@ShahrozTanveer `context.body()` works for me. This is not an `abc` issue, I will close it.

**Comment by ShahrozTanveer** [comment]
Issue resolved.
