### ISSUE TITLE
Parameter 'c' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by frunkad** [zhmushan/abc#78]
While deploying to Cloud Run, this line gave the error:

https://github.com/zhmushan/abc/blob/e301ae074570f2f41cf8cfdb584b7d3b26eff409/app.ts#L47

![image](https://user-images.githubusercontent.com/33373582/82557082-a4258000-9b88-11ea-980d-9337bdf0b3d3.png)

**Comment by zhmushan** [comment]
see #70 #76
