### ISSUE TITLE
Flasky syntax recommendation

### ISSUE THREAD

**Issue by therealadityashankar** [zhmushan/abc#8]
This is a recommendation/suggestion for a more elegant syntax, that has to be deno-specific as it REQUIRES ES6 or newer,
okay, here it goes

So, because of the way ES6 works, one can do this
```
routes = {
    "path/subpath":
    function routename(){
        return someresponse()
    },
    "path/anotherpath":
    function anotherRoutename(){
        return someresponse()
    },
}
```

hence all routes could be declared in an object and then a function like `app.employRoutes(routes)` could be used,
I could do a PR if wanted, 
anyway is this a good idea ?

**Comment by zhmushan** [comment]
Thank you and I prefer this
```ts
const routes = [
  {
    method: ["GET"],
    path: "/path/foo",
    handler: function() {},
    children: []
  }
]
```
Maybe we can extend `abc.add()` to support it.
If you have better suggestions, feel free to comment.

**Comment by therealadityashankar** [comment]
cool, love this! :heart: 
the children array `children:[]` is kind of a no-no for me though!, I'd rather separately define it, the code will get ugly if too many functions are defined in one place.

But yeah, neat!, love this !

**Comment by zhmushan** [comment]
Welcome to create PR for it!
