### ISSUE TITLE
Static path conflicting with get routes

### ISSUE THREAD

**Issue by LarsVomMars** [zhmushan/abc#80]
Hey,

playing around with static folders and get routes i realized that if you serve static files at root '/' it conflicts with *all* other get routes. 

```Typescript
app.static('/', './public/')
app.get("/test", async ctx => await ctx.json({success: true}));
```

This code results in following error:

```
error: Uncaught Error: '/test' in new path '/test' conflicts with existing wildcard '/*filepath' in existing prefix '/*filepath'
              throw new Error(
                    ^
    at Node.addRoute (https://deno.land/x/router@v0.1.0/node.ts:150:21)
    at Router.add (https://deno.land/x/abc/router.ts:21:10)
    at Application.add (https://deno.land/x/abc/app.ts:151:17)
    at Application.get (https://deno.land/x/abc/app.ts:97:17)
    at file://.../app.ts:27:5
```

FYI: 
I bypassed the problem by only serving special static files at their regarding routes and then rendering the html files with their routes.
e.g.

```Typescript
app.renderer = {
    render<T>(name: string, data?: T): Promise<Deno.Reader> {
        return renderFile(name, data!);
    },
};

app
    .static("/js", "./public/js")
    .static("/css", "./public/css")

app.get("/", async ctx => await ctx.render("./public/index.html"));
app.get("/test", async ctx => await ctx.json(ctx.cookies));
```

This might somehow be related to #67.
I don't know if this is/was intended regarding the previously mentioned issue :)

~ Lars

P.S.: To be clear there is no directory named *test* in *public/*

**Comment by zhmushan** [comment]
I am rewriting the router. Ideally, we should always match static routes first instead of throwing conflict exceptions

**Comment by zhmushan** [comment]
@LarsVomMars Fixed in https://github.com/zhmushan/abc/commit/ad63d65ec0f73bfeabc3bc80fb1ae6ae5e25904f
