### ISSUE TITLE
CORS Access-Control-Allow-Headers don't get set from 'allowHeaders[]' entries

### ISSUE THREAD

**Issue by Schoude** [zhmushan/abc#81]
Hi there!

It seems that the Header Types in the cors config don't get set from the allowHeaders array for `Access-Control-Allow-Headers`.
in [cors.ts](https://deno.land/x/abc@v1.0.0-rc6/middleware/cors.ts) line 82-85 only the `Header.AccessControlRequestHeaders` get set and not `Header.AccessControlAllowHeaders`.

Therefore Headers like `Content-Type` on the Response Headers don't get recognized and the request gets blocked.

Maybe you could add

```
resp.headers.set(
  Header.AccessControlAllowHeaders,
  config.allowHeaders.join(",")
);
```
to the if-block starting in line 81.

If there is something I am missing in my cors config that fixes the problem, please let me know!
Have a nice weekend!

**Comment by zhmushan** [comment]
@Schoude Oops, my bad. And thanks for pointing it out.

**Comment by Schoude** [comment]
@zhmushan No problem. Looking forward to v1.0.0.

**Comment by zhmushan** [comment]
Fixed in https://github.com/zhmushan/abc/commit/b8254950350555ff28279cc9798375e66fe49e1e
