### ISSUE TITLE
1.0

### ISSUE THREAD

**Issue by zhmushan** [zhmushan/abc#83]
The current version (`1.0.0-rc8`) is infinitely close to `1.0`, I believe I will no longer make breaking changes to the main API, e.g., `application`, `context`, etc.

But before 1.0 is released, I still need to do something:

- Richer tests: I need to add richer test cases to the [router module](https://github.com/zhmushan/router) to ensure that the routing works correctly in any case.

- Friendly docs: There should be a guide covering all APIs from beginner to intermediate.

- Refactored `deps.ts` and` dev_deps.ts`: In `deps.ts`, there are two import methods (`import * as`, `import {...}`). We should always use `import * as` to prevent namespace conflicts.

- Provide `session` support in the form of middleware: Although this is more like what the community needs to do, I still want to collect it in this repo. (because I need this function)

**Comment by zhmushan** [comment]
**Need to inform**: Due to the final exam, I will continue to do this after June 20.

**Comment by zhmushan** [comment]
landed on https://github.com/zhmushan/abc/commit/ea5ce3445fba6b1285f89eca99b8145be75d3b94

**Comment by huydhoang** [comment]
@zhmushan Hi Mu Shan, I see in #79 that you don't want to maintain multi language docs. Is it okay if I just add some guides and code examples for the English docs?
Not sure where to ask this question, so I'm placing it here.
In a broader sense, what are other areas you think can be improved in this project?

**Comment by zhmushan** [comment]
@huydhoang of course!  All reasonable documents and examples will be accepted.

And thank you for your attention to this project. I will plan the roadmap as soon as possible

**Comment by huydhoang** [comment]
@zhmushan You're welcome :-) I find this project interesting because of its simplicity, and also of how responsive you are.
Will look forward to your roadmap.
