### ISSUE TITLE
Object is of type 'unknown'.

### ISSUE THREAD

**Issue by gurubaksh** [zhmushan/abc#86]
const register: HandlerFunc = async (c) => {
let registrationData = await c.body();   // on console.log { username: "gurubaksh", password: "password" }

console.log(typeof registrationData);  //object
console.log(registrationData.username);  // also tried console.log(registrationData['username']);
return 1;
};

when run above code i am getting below error

Compile file:///F:/deno/main.ts
error: TS2571 [ERROR]: Object is of type 'unknown'.
 console.log(registrationData.username);

**Comment by zhmushan** [comment]
@gurubaksh 
```ts
interface User {
  username: string;
  password: string;
}

const register: HandlerFunc = async (c) => {
  let registrationData = await c.body<User>();

  console.log(typeof registrationData);
  console.log(registrationData.username);
  return 1;
};
```
