### ISSUE TITLE
Accessing file information in request?

### ISSUE THREAD

**Issue by JipFr** [zhmushan/abc#87]
I am POSTing files to my back-end, and `ctx.body()` would appear to give me the image. Now, is it possible to get the file names? 

Also, how can I proxy the image? When I use the following code (not exactly, the actual code has some authentication code)
```js
fetch(myUrl, {
  method: "PUT",
  body: await ctx.body()
});
``` 
it doesn't appear to be valid. It's possible this is an issue with the service I'm uploading to (it's supposed to PUT, their client has it that way as well), but I think that's unlikely.

**Comment by zhmushan** [comment]
The server cannot know what the file name is unless it is carried when sending the request:
```ts
fetch(`${myUrl}?fname=${fname}`, ...)
```

**Comment by JipFr** [comment]
I see. Does this also go for content-type ?

**Comment by JipFr** [comment]
Aw, it'd appear it's still not working on their file server, but I'm going to assume that's something to do with them or my code, not abc. Thanks for the help!
