### ISSUE TITLE
Examples on how to use route middlewares.

### ISSUE THREAD

**Issue by dereksangshi2000** [zhmushan/abc#89]
The route middlewares and handlers are chained functions which is an unusual implementation. I think we need some examples here since it could be hard to debug when you don't see the proper http response.

```
app.post(
    "/my-path", 
    myHandler, // This will get called lastly.
    myMiddleware1, // This will get called secondly
    myMiddleware2 // This will get called firstly
);

const myMiddleware1: MiddlewareFunc = next => async (c: Context): Promise<any> => {
    // next(c); This will not return the result returned by 'myHandler'. The same for 'myMiddleware2'.
    // Do return here, or anything returned or updated by myHandler will be missed.
    return next(c);
}
```

**Comment by zhmushan** [comment]
I agree.

I am finishing the guides, but you know, this is not an easy job, I need a little time.

**Comment by zhmushan** [comment]
see https://github.com/zhmushan/abc/commit/1b5cc629a54e2245859cbfe3249c5faac85fd49d
