### ISSUE TITLE
SPA routing (fallback to index.html)

### ISSUE THREAD

**Issue by tlindstrom** [zhmushan/abc#90]
For apps with client-side navigation, I would typically want to set up my routing like this:

1. Try to match any hardcoded API routes
2. Try to match static files from a /static directory
3. Everything else falls back to returning index.html

Something like this:

```
app
  .get("/api/potato", (c) => { return potato; })
  .static('/', 'static')
  .file('*', 'static/index.html')
  .start({ port: 8080 });
```

This fails, with this error:
`Uncaught Error: a function is already registered for path "*"`

Has this use case been considered? Is there a mechanism in place for this use case?

**Comment by zhmushan** [comment]
Hi @tlindstrom 
I think this issue has been fixed in the latest version.
see #67

**Comment by zhmushan** [comment]
Sorry, I didn't understand what you meant before.

Plz try this:
```ts
import { Application, NotFoundException } from "https://deno.land/x/abc@v1/mod.ts";

const app = new Application();

app
  .get("/api/potato", (c) => {
    return "potato";
  })
  .static("/", "static", next => {
    return async c => {
      try {
        await next(c);
      } catch (e) {
        if (e instanceof NotFoundException) {
          return c.redirect("/index.html");
        }
        
        throw e;
      }
    }
  })
  .start({ port: 8080 });

```
