### ISSUE TITLE
Could not set cookie

### ISSUE THREAD

**Issue by huydhoang** [zhmushan/abc#94]
I'm trying to set and get cookie, like this:
`context.setCookie({ name: "token", value: myValue, sameSite: "Strict" });`
and then read it like this:
`token = context.cookies.get("token");`
But that did not work. I couldn't find any guide how to set & get cookie in the docs and examples.
Could anyone please point me to the right direction?

**Comment by zhmushan** [comment]
`setCookie()` is to set the cookie to the response header, and `context.cookie` is to parse the cookie from the request header

**Comment by huydhoang** [comment]
> `setCookie()` is to set the cookie to the response header, and `context.cookie` is to parse the cookie from the request header

@zhmushan thanks for the reply. actually I mistakenly thought the first one didn't work. context.setCookie() definitely works.
But for parsing, I had to use context.cookies.token. I'm on abc@v1.
So consider this issue closed.
