### ISSUE TITLE
WebSocket example is not working

### ISSUE THREAD

**Issue by huydhoang** [zhmushan/abc#95]
**Example taken from here:** https://github.com/zhmushan/abc/blob/master/examples/websocket/server.ts

**Expected outcome:** "server listening on http://localhost:8080"

**Current outcome:** app crashed with bufReader and bufWriter assignment errors (missing required property?)
Example works when modifying dep versions to the following:
"https://deno.land/x/abc@v1.0.0/mod.ts";
"https://deno.land/std@0.59.0/ws/mod.ts"

**Steps to reproduce:**

Deno: v1.2.1
std/0.62
abc: master
`deno upgrade --version 1.2.1`
`deno run -A abc-ws.ts `

```
import {
  Application,
  HandlerFunc,
} from "https://deno.land/x/abc@master/mod.ts";

import { acceptWebSocket } from "https://deno.land/std/ws/mod.ts";

const app = new Application();

const hello: HandlerFunc = async (c) => {
  const { conn, headers, r: bufReader, w: bufWriter } = c.request;
  const ws = await acceptWebSocket({
    conn,
    headers,
    bufReader,
    bufWriter,
  });

  for await (const e of ws) {
    console.log(e);
    await ws.send("Hello, Client!");
  }
};

app.get("/ws", hello).file("/", "./index.html").start({ port: 8080 });

console.log(`server listening on http://localhost:8080`);

```

```
Download https://deno.land/x/abc@master/mod.ts
Download https://deno.land/x/abc@master/app.ts
Download https://deno.land/x/abc@master/group.ts
Download https://deno.land/x/abc@master/context.ts
Download https://deno.land/x/abc@master/router.ts
Download https://deno.land/x/abc@master/types.ts
Download https://deno.land/x/abc@master/http_exception.ts
Download https://deno.land/x/abc@master/vendor/https/deno.land/std/path/mod.ts
Download https://deno.land/x/abc@master/util.ts
Download https://deno.land/x/abc@master/vendor/https/deno.land/std/http/server.ts
Download https://deno.land/x/abc@master/vendor/https/deno.land/std/http/http_status.ts
Download https://deno.land/x/abc@master/vendor/https/deno.land/x/router/mod.ts
Download https://deno.land/x/abc@master/vendor/https/deno.land/std/http/cookie.ts
Download https://deno.land/x/abc@master/vendor/https/deno.land/std/mime/multipart.ts
Download https://deno.land/x/abc@master/vendor/https/deno.land/std/encoding/utf8.ts
Download https://deno.land/x/abc@master/constants.ts
Check deno-sandbox/abc-ws.ts
error: TS2322 [ERROR]: Type 'import("https://deno.land/std@0.62.0/io/bufio").BufReader' is not assignable to type 'import("https://deno.land/std/io/bufio").BufReader'.
  Types have separate declarations of a private property 'buf'.
    bufReader,
    ~~~~~~~~~
    at deno-sandbox/abc-ws.ts:15:5

    The expected type comes from property 'bufReader' which is declared here on type '{ conn: Conn; bufWriter: BufWriter; bufReader: BufReader; headers: Headers; }'
      bufReader: BufReader;
      ~~~~~~~~~
        at https://deno.land/std/ws/mod.ts:421:3

TS2322 [ERROR]: Type 'import("https://deno.land/std@0.62.0/io/bufio").BufWriter' is not assignable to type 'import("https://deno.land/std/io/bufio").BufWriter'.
  Types have separate declarations of a private property 'writer'.
    bufWriter,
    ~~~~~~~~~
    at deno-sandbox/abc-ws.ts:16:5

    The expected type comes from property 'bufWriter' which is declared here on type '{ conn: Conn; bufWriter: BufWriter; bufReader: BufReader; headers: Headers; }'
      bufWriter: BufWriter;
      ~~~~~~~~~
        at https://deno.land/std/ws/mod.ts:420:3

Found 2 errors.
```

**Comment by LarsVomMars** [comment]
For me this only happens with `std@master` (or rather `std@0.63.0` atm), `std@<=0.62.0` seems to work fine - like you said.

When using the [given websocket example](https://github.com/zhmushan/abc/blob/master/examples/websocket/server.ts) with relative imports from [/vendor/*](https://github.com/zhmushan/abc/blob/master/vendor/), bumping all std dependencies in `/vendor/*` from std@0.62.0 to std@0.63.0 works tho. IDK why!

Tested both with deno 1.2.1 and 1.2.2 on Arch.

**Comment by LarsVomMars** [comment]
Ok, so the std version defined in the `abc` vendor is another one (in this case lower) than the version of the write-/read-buffers required by the `acceptWebSocket` (which you require separately from deno) function, which causes this error. 
That also should be the reason why bumping all std versions in `/vendor/*` solves this issue.

~ Lars

**Comment by huydhoang** [comment]
Thanks for the reply @LarsVomMars ! Unfortunately, it's still complaining.
I'm importing from direct links instead of from /vendor. But how could that be any difference?
I thought the vendor folder was just a mirror for all deps (?)

Tested with deno 1.2.1 and 1.2.2, same errors.
I'm on Pop OS (Ubuntu 20.04).

```
denon run -A abc-ws.ts 
Check https://deno.land/x/denon@v2.2.1/denon.ts
[denon] v2.2.1
[denon] watching path(s): *.*
[denon] watching extensions: ts,tsx,js,jsx,json
[denon] starting `deno run -A abc-ws.ts`
Check deno-sandbox/abc-ws.ts
error: TS2322 [ERROR]: Type 'import("https://deno.land/std@0.61.0/io/bufio").BufReader' is not assignable to type 'import("https://deno.land/std@0.62.0/io/bufio").BufReader'.
  Types have separate declarations of a private property 'buf'.
    bufReader,
    ~~~~~~~~~
    at deno-sandbox/abc-ws.ts:15:5

    The expected type comes from property 'bufReader' which is declared here on type '{ conn: Conn; bufWriter: BufWriter; bufReader: BufReader; headers: Headers; }'
      bufReader: BufReader;
      ~~~~~~~~~
        at https://deno.land/std@0.62.0/ws/mod.ts:421:3

TS2322 [ERROR]: Type 'import("https://deno.land/std@0.61.0/io/bufio").BufWriter' is not assignable to type 'import("https://deno.land/std@0.62.0/io/bufio").BufWriter'.
  Types have separate declarations of a private property 'writer'.
    bufWriter,
    ~~~~~~~~~
    at deno-sandbox/abc-ws.ts:16:5

    The expected type comes from property 'bufWriter' which is declared here on type '{ conn: Conn; bufWriter: BufWriter; bufReader: BufReader; headers: Headers; }'
      bufWriter: BufWriter;
      ~~~~~~~~~
        at https://deno.land/std@0.62.0/ws/mod.ts:420:3

Found 2 errors.
```

**Comment by LarsVomMars** [comment]
Have you tried to reload all the dependencies with: `deno run -A --reload abc-ws.ts`?

**Comment by huydhoang** [comment]
`--reload` didn't work but downgrading to `std@0.61.0` works with `abc@1.0.1`.
It seems inline with this import statement: https://deno.land/x/abc@v1.0.1/vendor/https/deno.land/std/ws/mod.ts

**Comment by zhmushan** [comment]
@huydhoang Try to use abc@v1 & std@0.63.0, with `--reload`. (I just upgraded the deps

**Comment by LarsVomMars** [comment]
Like I said in my second comment here:
When importing `acceptWebSocket` from deno it uses another std version (and so requires another version of the buffers) than the abc context's request (c.request) returns.

**Comment by huydhoang** [comment]
@LarsVomMars I see, that makes sense. But is it not that we must import acceptWebSocket from Deno std in order to establish a connection? :roll_eyes: 
@zhmushan I just checked, latest versions working are still `abc@v1.0.1` and `std@0.61.0`. Is there a delay in syncing between github and deno.land's mirror? :package:
