### ISSUE TITLE
403 Forbidden while trying to download library

### ISSUE THREAD

**Issue by johny1614** [zhmushan/abc#99]
Minimal reproduction steps: 

Create file.ts with code:
`import { Application } from "https://deno.land/x/abc@v1/mod.ts";`

And run command:

> sudo deno run  --allow-read --allow-net --allow-plugin --unstable file.ts

Actual results: script shuts down on 1 line - console prints:

```
Download https://deno.land/x/abc@v1/mod.ts
Download https://deno.land/std@v0.50.0/fs/exists.ts
Download https://deno.land/std@v0.50.0/log/mod.ts
Download https://deno.land/std@v0.50.0/path/mod.ts
error: Import 'https://deno.land/x/abc@v1/mod.ts' failed: 403 Forbidden
Imported from "file:///Users/someUser/someFolder/file.ts:1"

```

**Comment by LarsVomMars** [comment]
This is due to some [updates to the deno module system](https://deno.land/posts/registry2).

**Comment by zhmushan** [comment]
I don’t know how to create a webhook correctly, can anyone tell me what to fill in `Payload URL`?

**Comment by zhmushan** [comment]
@johny1614 fixed
